version: '3.1'

services:
  aiim-frontend:
    container_name: aiim-frontend_container
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - aiim-backend
  aiim-api:
    container_name: aiim-api_container
    build:
      context: ./api/
      dockerfile: Dockerfile
    ports:
      - 3005:3005
    depends_on:
      - aiim-db
  aiim-db:
    container_name: aiim-db_container
    image: 'prismagraphql/mongo-single-replica:4.4.3-bionic'
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGODB_DATABASE}
      INIT_WAIT_SEC: 3
    volumes:
      - ./docker-data/db:/data/db
      # - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - 27017:27017
