version: '3.1'

services:
  aiim-frontend:
    container_name: aiim-frontend_container
    restart: unless-stopped
    build: ./frontend
    ports:
      - 3000:3000
    depends_on:
      - aiim-api
    environment:
      NUXT_PUBLIC_API_BASE_URL: ${NUXT_PUBLIC_API_BASE_URL}
  aiim-api:
    container_name: aiim-api_container
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./api/Dockerfile
    ports:
      - 3005:3005
    depends_on:
      - aiim-db
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRE_TIME: ${JWT_EXPIRE_TIME}
      SIGN_PASS: ${SIGN_PASS}
  aiim-db:
    image: 'bitnami/mongodb:4.4.3'
    restart: unless-stopped
    environment:
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_PRIMARY_HOST=localhost
      - MONGODB_ADVERTISED_HOSTNAME=localhost
      - MONGODB_REPLICA_SET_KEY=replicakeyyy
      - MONGODB_USERNAME=${MONGODB_USERNAME}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - MONGODB_ROOT_PASSWORD=${MONGODB_PASSWORD}
      - MONGODB_DATABASE=${MONGODB_DATABASE}
    volumes:
      - 'aiim-db_data:/bitnami/mongodb'
    ports:
      - 27017:27017
  aiim-redis:
    image: redis:7.0.5
    restart: unless-stopped
    ports:
      - 6379:6379

volumes:
  aiim-db_data:
